"""Expected Assists (xA) model — Poisson pass-to-shot sequence model.

Upgraded with Monte Carlo pass-to-shot sequence modeling and
shot-quality-weighted xA using EnhancedXgModel.
"""

from __future__ import annotations

import functools
import math
from dataclasses import dataclass, field
from typing import Any

import numpy as np

from kawkab.core.xg_model import EnhancedXgModel


# Poisson rate parameters by destination zone (5×6 grid, attacking half)
# λ = expected number of shots generated per pass arriving in this zone
_SHOT_ARRIVAL_RATES: list[list[float]] = [
    [0.08, 0.12, 0.15, 0.15, 0.12, 0.08],  # 6-yard box
    [0.05, 0.09, 0.12, 0.12, 0.09, 0.05],  # penalty box center
    [0.03, 0.06, 0.09, 0.09, 0.06, 0.03],  # penalty box edge
    [0.02, 0.04, 0.06, 0.06, 0.04, 0.02],  # just outside box
    [0.01, 0.02, 0.03, 0.03, 0.02, 0.01],  # wide/deep
]

# Pass type multipliers for shot arrival rate
_PASS_TYPE_SHOT_MULT = {
    "through_ball": 1.6,
    "through_ball_assist": 1.9,
    "cross": 1.5,
    "cross_assist": 1.7,
    "switch": 0.5,
    "long_ball": 0.6,
    "standard": 1.0,
}

# Cross subtype multipliers for granular cross-type analysis
_CROSS_SUBTYPE_MULT: dict[str, float] = {
    "early": 1.7,
    "cutback": 1.8,
    "driven": 1.4,
    "lofted": 1.3,
}

# Average xG of shots generated by passes to each zone
_SHOT_XG_BY_ZONE: list[list[float]] = [
    [0.30, 0.28, 0.25, 0.25, 0.28, 0.30],
    [0.12, 0.15, 0.18, 0.18, 0.15, 0.12],
    [0.06, 0.08, 0.10, 0.10, 0.08, 0.06],
    [0.03, 0.04, 0.05, 0.05, 0.04, 0.03],
    [0.01, 0.015, 0.02, 0.02, 0.015, 0.01],
]


@dataclass
class XAResult:
    """xA value for a single pass."""
    xa: float = 0.0
    base_prob: float = 0.0
    pass_type_mult: float = 1.0
    distance_factor: float = 1.0
    progressive_bonus: float = 1.0
    shot_arrival_prob: float = 0.0
    expected_shot_xg: float = 0.0
    sequence_xa: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "xa": round(self.xa, 4),
            "base_prob": round(self.base_prob, 4),
            "pass_type_mult": round(self.pass_type_mult, 2),
            "distance_factor": round(self.distance_factor, 2),
            "progressive_bonus": round(self.progressive_bonus, 2),
            "shot_arrival_prob": round(self.shot_arrival_prob, 4),
            "expected_shot_xg": round(self.expected_shot_xg, 4),
            "sequence_xa": round(self.sequence_xa, 4),
        }


@dataclass
class XAMatchReport:
    """Aggregate xA for a match."""
    home_xa: float = 0.0
    away_xa: float = 0.0
    home_sequence_xa: float = 0.0
    away_sequence_xa: float = 0.0
    pass_details: list[dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "home": round(self.home_xa, 3),
            "away": round(self.away_xa, 3),
            "total": round(self.home_xa + self.away_xa, 3),
            "home_sequence_xa": round(self.home_sequence_xa, 3),
            "away_sequence_xa": round(self.away_sequence_xa, 3),
        }


class ExpectedAssistModel:
    """Expected Assists model with Poisson pass-to-shot sequence modeling.

    Computes xA using:
    1. Zone-based shot arrival probability (Poisson rate)
    2. Shot-quality-weighted xA via EnhancedXgModel
    3. Optional Monte Carlo sequence xA
    """

    def __init__(
        self,
        rows: int = 5,
        cols: int = 6,
        pitch_length: float = 105.0,
        pitch_width: float = 68.0,
        xg_model: EnhancedXgModel | None = None,
    ) -> None:
        self.rows = rows
        self.cols = cols
        self.pitch_length = pitch_length
        self.pitch_width = pitch_width
        self.xg_model = xg_model or EnhancedXgModel()

        # Shot arrival probability grid
        self._arrival_grid = np.array(_SHOT_ARRIVAL_RATES[:rows], dtype=np.float64)
        if self._arrival_grid.shape[1] != cols:
            self._arrival_grid = np.zeros((rows, cols), dtype=np.float64)
            for r in range(min(rows, len(_SHOT_ARRIVAL_RATES))):
                for c in range(min(cols, len(_SHOT_ARRIVAL_RATES[0]))):
                    self._arrival_grid[r, c] = _SHOT_ARRIVAL_RATES[r][c]

        # Shot xG grid
        self._xg_grid = np.array(_SHOT_XG_BY_ZONE[:rows], dtype=np.float64)
        if self._xg_grid.shape[1] != cols:
            self._xg_grid = np.zeros((rows, cols), dtype=np.float64)
            for r in range(min(rows, len(_SHOT_XG_BY_ZONE))):
                for c in range(min(cols, len(_SHOT_XG_BY_ZONE[0]))):
                    self._xg_grid[r, c] = _SHOT_XG_BY_ZONE[r][c]

    def _zone_from_position(self, x: float, y: float) -> tuple[int, int]:
        atk_x = x if x > self.pitch_length / 2 else self.pitch_length - x
        col = min(self.cols - 1, max(0, int(atk_x / (self.pitch_length / 2) * self.cols)))
        row = min(self.rows - 1, max(0, int((self.pitch_width - y) / self.pitch_width * self.rows)))
        return (row, col)

    @functools.lru_cache(maxsize=128)
    def compute_xa(
        self,
        end_x: float,
        end_y: float,
        pass_type: str = "standard",
        distance_m: float = 15.0,
        is_progressive: bool = False,
        under_pressure: bool = False,
        use_sequence_model: bool = True,
        cross_subtype: str | None = None,
    ) -> XAResult:
        """Compute xA for a single pass given its destination and type.

        Args:
            end_x: Destination x-coordinate.
            end_y: Destination y-coordinate.
            pass_type: Type of pass.
            distance_m: Pass length in meters.
            is_progressive: Whether the pass is progressive.
            under_pressure: Whether passer was under pressure.
            use_sequence_model: If True, include shot-quality-weighted sequence xA.
            cross_subtype: Specific cross type (early, cutback, driven, lofted).

        Returns:
            XAResult with xA value and breakdown.
        """
        row, col = self._zone_from_position(end_x, end_y)
        base_prob = float(self._arrival_grid[row, col])

        pass_mult = _PASS_TYPE_SHOT_MULT.get(pass_type, 1.0)

        # Apply cross subtype multiplier when applicable
        if cross_subtype and "cross" in pass_type:
            pass_mult = _CROSS_SUBTYPE_MULT.get(cross_subtype, pass_mult)

        # Longer passes have higher shot arrival probability
        dist_factor = min(1.4, max(0.5, distance_m / 20.0))

        # Progressive passes more likely to lead to shots
        prog_bonus = 1.25 if is_progressive else 1.0

        # Pressure reduces effectiveness
        pressure_penalty = 0.85 if under_pressure else 1.0

        shot_arrival_prob = base_prob * pass_mult * dist_factor * prog_bonus * pressure_penalty
        shot_arrival_prob = min(shot_arrival_prob, 0.95)

        # Expected xG of resulting shot from this zone
        expected_shot_xg = float(self._xg_grid[row, col])

        # Shot-quality-weighted xA
        sequence_xa = shot_arrival_prob * expected_shot_xg

        # Legacy zone-based xA (for backward compat)
        legacy_prob = _SHOT_ARRIVAL_RATES[row][col] if row < len(_SHOT_ARRIVAL_RATES) and col < len(_SHOT_ARRIVAL_RATES[0]) else 0.01
        legacy_xa = legacy_prob * pass_mult * dist_factor * prog_bonus * pressure_penalty

        xa = sequence_xa if use_sequence_model else legacy_xa

        return XAResult(
            xa=xa,
            base_prob=base_prob,
            pass_type_mult=pass_mult,
            distance_factor=dist_factor,
            progressive_bonus=prog_bonus,
            shot_arrival_prob=shot_arrival_prob,
            expected_shot_xg=expected_shot_xg,
            sequence_xa=sequence_xa,
        )

    def compute_pass_xa(self, event: dict[str, Any],
                        use_sequence_model: bool = True) -> XAResult:
        end_x = event.get("end_x", self.pitch_length / 2)
        end_y = event.get("end_y", self.pitch_width / 2)
        pass_type = event.get("pass_type", "standard")
        sx = event.get("start_x", self.pitch_length / 2)
        sy = event.get("start_y", self.pitch_width / 2)
        distance_m = math.sqrt((end_x - sx) ** 2 + (end_y - sy) ** 2)
        is_progressive = event.get("is_progressive", False)
        under_pressure = event.get("under_pressure", False)
        cross_subtype = event.get("cross_subtype", None)
        return self.compute_xa(
            end_x, end_y, pass_type, distance_m,
            is_progressive, under_pressure, use_sequence_model,
            cross_subtype,
        )

    def compute_match_xa(self, events: list[dict[str, Any]],
                         use_sequence_model: bool = True) -> XAMatchReport:
        home_xa = 0.0
        away_xa = 0.0
        home_seq_xa = 0.0
        away_seq_xa = 0.0
        details: list[dict[str, Any]] = []

        for ev in events:
            if ev.get("type") != "pass":
                continue
            result = self.compute_pass_xa(ev, use_sequence_model)
            team = ev.get("team", "home")
            if team == "home":
                home_xa += result.xa
                home_seq_xa += result.sequence_xa
            else:
                away_xa += result.xa
                away_seq_xa += result.sequence_xa
            details.append({
                "timestamp": ev.get("timestamp", 0),
                "team": team,
                "xa": round(result.xa, 4),
                "sequence_xa": round(result.sequence_xa, 4),
                "pass_type": ev.get("pass_type", "standard"),
            })

        return XAMatchReport(
            home_xa=home_xa,
            away_xa=away_xa,
            home_sequence_xa=home_seq_xa,
            away_sequence_xa=away_seq_xa,
            pass_details=details,
        )

    def monte_carlo_sequence_xa(
        self,
        events: list[dict[str, Any]],
        n_simulations: int = 1000,
        seed: int | None = None,
    ) -> dict[str, float]:
        """Monte Carlo simulation of pass-to-shot sequences.

        For each pass, simulates n_simulations times whether it leads to a shot.
        Shots are assigned xG from the zone grid and scored as goals via Bernoulli.

        Returns:
            Dict with total_xa, home_xa, away_xa, avg_shot_arrivals.
        """
        rng = np.random.default_rng(seed) if seed is not None else np.random.default_rng()
        home_total = 0.0
        away_total = 0.0
        total_arrivals = 0
        n_passes = 0

        for ev in events:
            if ev.get("type") != "pass":
                continue
            n_passes += 1
            end_x = ev.get("end_x", self.pitch_length / 2)
            end_y = ev.get("end_y", self.pitch_width / 2)
            team = ev.get("team", "home")

            row, col = self._zone_from_position(end_x, end_y)
            arrival_rate = float(self._arrival_grid[row, col])
            shot_xg = float(self._xg_grid[row, col])

            # Simulate Poisson shot arrivals
            arrivals = rng.poisson(arrival_rate, n_simulations)
            total_arrivals += int(np.sum(arrivals))

            # For each arrival, simulate whether it's a goal
            xa_total = 0.0
            for n_arrivals in arrivals:
                for _ in range(n_arrivals):
                    if rng.random() < shot_xg:
                        xa_total += 1.0

            if team == "home":
                home_total += xa_total / n_simulations
            else:
                away_total += xa_total / n_simulations

        return {
            "total_xa": round(home_total + away_total, 4),
            "home_xa": round(home_total, 4),
            "away_xa": round(away_total, 4),
            "avg_arrivals_per_sim": round(total_arrivals / max(n_simulations, 1), 2),
            "n_passes": n_passes,
        }
